"""empty message

Revision ID: 249043c1ae11
Revises: 73ec92f69856
Create Date: 2018-10-24 23:17:39.060709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249043c1ae11'
down_revision = '73ec92f69856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('location', sa.String(length=200), nullable=True))
    op.drop_column('room', 'locaton')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('locaton', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('room', 'location')
    # ### end Alembic commands ###
