"""empty message

Revision ID: 73ec92f69856
Revises: 
Create Date: 2018-10-24 23:16:25.088769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ec92f69856'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('locaton', sa.String(length=200), nullable=True))
    op.drop_column('room', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('room', 'locaton')
    # ### end Alembic commands ###
