"""empty message

Revision ID: a625637b64cc
Revises: 249043c1ae11
Create Date: 2018-10-24 23:20:30.028603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a625637b64cc'
down_revision = '249043c1ae11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('number_of_rooms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'number_of_rooms')
    # ### end Alembic commands ###
